// File generated by 'bdfe -r -s 32-126 atari-small.bdf'
// https://github.com/achilikin/bdfe
//
// COMMENT
// COMMENT  Copyright (c) 1999, Thomas A. Fine
// COMMENT
// COMMENT  License to copy, modify, and distribute for both commercial and
// COMMENT  non-commercial use is herby granted, provided this notice
// COMMENT  is preserved.
// COMMENT
// COMMENT  Email to my last name at head.cfa.harvard.edu
// COMMENT  http://hea-www.harvard.edu/~fine/
// COMMENT
// COMMENT  Produced with bdfedit, a tcl/tk font editing program
// COMMENT  written by Thomas A. Fine
// COMMENT
// FONT -atari-small
// FONTBOUNDINGBOX 4 8 0 -1
// FONT_DESCENT 1
// FONT_ASCENT 7
// COPYRIGHT "Copyright 1999 by Thomas A. Fine"
// Converted Font Size 4x8

#ifndef __BIT8_FONT_4
#define __BIT8_FONT_4

#include "bit8_txt.h"

extern const bit8_txt_font_t bit8_txt_font_4;

#endif
